### ISSUE TITLE
Streamline setting of inputs in Main.R when running with only "Current"

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#133]
At the moment, it is difficult for the user to understand how to set several inputs within Main.R when running with only current ("Current") conditions. For example:

```
#Difference between start and end year(if you want 2030-2060 use 50; if you want 2070-2100 use 90 below)
    deltaFutureToSimStart_yr <- c("d50","d90")
    
    #Downscaling method
    downscaling.method <- c("hybrid-delta-3mod")
```
`YEARS<-c("d50yrs","d90yrs")`
`RCP<-c("RCP45","RCP85")`

None of these inputs are relevant for current conditions. I believe they are completely ignored if  running with "Current" only, in which case we need to update the comments to document this to the user. If that is not the case, we need to consider a new code flow that is more conductive for testing under current conditions only.

**Comment by chaukap** [comment]
@kpalmqui I just pushed a correction to our problem of the code crashing when trying to run only "Current" conditions. I tested my change by removing all RCPs and GCMs like this:
```
GCM<-c("Current")
RCP<-c()
```
I also plan on testing without modifying the RCP at all.

**Comment by kpalmqui** [comment]
@chaukap sounds good. Whatever solution works, let's be sure to add comments accordingly in Main.R.

**Comment by chaukap** [comment]
@kpalmqui 
I just tried setting `climate.conditions` to "Current" only and not changing any other variables. Program completed with all of the requested output, however there were "No such file or directory" errors caused by the variable GCM. This lead me to evaluate the variables and I think there is some room to streamline `climate.conditions`, `GCM` and `RCP`. 
```
climate.conditions <- c(climate.ambient,  "RCP45.CanESM2", "RCP45.CESM1-CAM5", "RCP45.CSIRO-Mk3-6-0", "RCP45.FGOALS-g2", "RCP45.FGOALS-s2", ... ,)
```
```
GCM<-c("Current","CanESM2","CESM1-CAM5","CSIRO-Mk3-6-0","FGOALS-g2","FGOALS-s2", ... ,)
RCP<-c("RCP45","RCP85")
```
This is my understanding of the variables:
* `climate.conditions` is every combination of RCPs and GCMs we want to use.
* `GCM` is every GCM present in `climate.conditions`
* `RCP` is every RCP present in `weather.conditions`

This means that omitting a GCM from `GCM` that is present in `climate.conditions` will result in that GCM being ignored by CallSTEPWAT2.R, and inversely omitting a GCM from `climate.conditions` that is present in `GCM` will throw a "file not found" error.

Since `GCM` and `RCP` are both derived from `climate conditions` why not create them programmatically? We could scan `climate.conditions`, parse it for all GCMs and RCPs, and assign the variables. In pseudocode:
```
for(x in climate.conditions){
   split x at the period
   let y be the first string and z be the second string
   if y is not in RCP, add it to RCP
   if z is not in GCM, add it to GCM
}
```
An example of parsing "RCP45.CanESM2" using the algorithm:
```
x <- "RCP45.CanESM2"
f <- strsplit(x,"\\.")
y <- f[[1]][1]
z <- f[[1]][2]
RCP <- c(RCP, y)     # assuming "RCP45" is not present already
GCM <- c(GCM, z)     # assuming "CanESM2" is not present already
```

Let me know if my understanding of `GCM` and `RCP` are correct and I can start implementing this algorithm.

**Comment by kpalmqui** [comment]
@chaukap sounds great.

**Comment by kpalmqui** [comment]
@chaukap have you tested this new functionality on your machine? I just did and it failed. Looks like the GCM and RCP strings were not correctly parsed and set. See attached screenshot.

<img width="566" alt="Screen Shot 2019-06-12 at 10 15 59 AM" src="https://user-images.githubusercontent.com/7769797/59358851-53ac6e00-8cfb-11e9-9fec-fb0beba44a4f.png">

**Comment by chaukap** [comment]
@kpalmqui This was an oversight on my part. I forgot that downscaling methods were prepended to climate.conditions which was causing the issue. It should be resolved now, and I ran the code to completion without any problems.

**Comment by kpalmqui** [comment]
@chaukap I reran and it is now completing on my end as well. I believe we are ready to close this issue and open a pull request.
