### ISSUE TITLE
Bug resulting in NaN values for PPT_avg and p_W_W in mkv_prob.in

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#28]
There is a bug somewhere in Markov.Weather_V2.R the code that results in NaN values for PPT_avg and p_W_W.  These values can be 0, but never NaN. Perhaps somewhere values are being divided by 0?

Temporary checks have been put into place to reset these values to 0 (see d9d838aa1a61fdbbccaf44c2505d872754d12779), but these checks should be removed once the issue is resolved.

**Comment by kpalmqui** [comment]
For p_W_W, NaN is occasionally occurring when the number of total wet days from the previous day =0, which is divided by the number of wet given wet years for that day. 

Solution: added a check to see whether the number of total wet days =0, if so, then skip the division and set the probability to 0. 

The same applies to p_W_D.

**Comment by chaukap** [comment]
For p_W_W dividing by 0 will occur when the total number of wet days for the previous day (totalwet.doy1 or totalwet.notdoy1) equals 0. The formula for p_W_W is
```
sum(WW[day])/(totalwet for previous day)
```
where
```
WW[day] = (today is wet) && (yesterday was wet)
```
Therefore if (totalwet for previous day) == 0 then WW == 0 because (yesterday was wet) must be FALSE. 
The NaN values are being generated only in the case 
```
sum(WW[day])/(totalwet for previous day) == 0/0
```
Which mathematically is undefined, but for our definition for p_W_W should be 0.
```
0/0 = 0
```
The check
```
p_W_W<-ifelse(totalwet.doy1>0, p_W_W/totalwet.doy1, 0)
```
is therefore the correct solution to this bug. R will return NaN for 0/0 but we have defined 0/0 as 0.
