### ISSUE TITLE
Occasionally probability of wet and dry days are > 1.0 in mkv_prob.in file

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#31]
Occasionally, the probability of wet and dry days that are generated here and populated in the mkv_prob.in file are > 1. These values should be constrained between 0 to 1.

The code will fail when this occurs due to checks in SOILWAT2 in SW_Markov.c.

**Comment by kpalmqui** [comment]
Sites that fail without the built-in checks include:
From KP weather database:

79: p_w_w = 1.16
144: p_w_w = 1.14
826: p_w_w = 1.25
862: p_w_w = 1.2
876: p_w_w = 1.25

**Comment by chaukap** [comment]
Currently we believe that the problem comes from incomplete implementation of leap years. 
On year one many variables are set using data from from the previous year via a function like
```
<- dgf[i+364]
```
which clearly does not take into account leap years. I will try to recreate this issue and confirm that it is the problem.

**Comment by chaukap** [comment]
The problem actually had to do with the mapping of wet given wet. In row 1 of the DGF data frame WW was calculated using 
```
WET[1] & WET[365]
```
Every row after that was calculated using
```
WET[i] & WET[i-1]
```
for I = 366 (remember I am talking about row, not DOY)
```
WET[366] & WET[365]
```
Which means that WET[1] and WET[366] both depend on WET[365]. 

Example using 3 days and 6 rows.
--
In this example the equivalent to WET[365] is WET[3].
DOY    WET    WW    WD
1             T         T        F
2             T        T        F
3             T        T        F
1              T        T        F
2             F         F        F
3             F         F        F

summing probability of wet given wet for day 1 = 2
summing wet days for day 3 = 1
2/1 = 2

Solution
--
This in therefore not a one-to-one mapping and the weight of WET[365] should either be doubled or the first row should be calculated differently.

My solution was to make the function one-to-one by changing the calculation of WW in row 1 to
```
WET[1] & WET[last row]
```

This solution will correct the problem but could negatively affect row 1 since it is calculated using data that is as far away as possible. However, since we do not expect to see any massive changes in weather in a 30 year period it should not make a noticeable difference.
