### ISSUE TITLE
Source.dir should generate correct path based on type of OS

### ISSUE THREAD

**Issue by nompatil** [DrylandEcology/rSFSTEP2#42]
Source.dir variable  in Main.R is used to populate path automatically. Currently, for windows it takes Cygwin path but actual path of files are based on windows path. 

For e.g
source.dir<-"/cygdrive/c/rSFSTEP2/R_Program_1"

Actual Path : 
source.dir<-"C:/rSFSTEP2/R_Program_1/"

**Comment by kpalmqui** [comment]
@fdpierson I just assigned you to two issues that are open within this milestone. The goal here is to get rSFSTEP2 functional on Windows.

Since you have a Windows machine, I though this would be a relevant milestone for you to lead and will introduce you to rSFSTEP2. No need to begin immediately - we can discuss the timing of your work on this milestone during our meeting next Monday. For now, continue to work on gridded_code of STEPWAT2. Thanks!

**Comment by kpalmqui** [comment]
@fdpierson I believe this can be closed?

**Comment by fdpierson** [comment]
@kpalmqui Definitely.
