### ISSUE TITLE
Wrapper not creating all necessary .in files

### ISSUE THREAD

**Issue by chaukap** [DrylandEcology/rSFSTEP2#73]
I've been running through the code line by line and for the most part it looks good. The wrapper.code.R file is working correctly so far. 
However, the file 'rgroup.freq50.graz.0.lowgraz.in' is missing from the STEPWAT_DIST directory. 'rgroup.freq0.graz.0.lowgraz.in' and 'rgroup.freq50.graz.1.lowgraz.in' DO exist, so there must be a problem when instantiating 'rgroup.freq50.graz.0.lowgraz.in'.
I cannot move forward with wrapper.code.R unil this issue is resolved, so I will prioritize it.
My best guess is the issue is an incorrect for loop in wrapper.MAIN.R.

**Comment by kpalmqui** [comment]
'rgroup.freq50.graz.0.lowgraz.in' is missing because that combination was not specified in the InputData_Rgroup.csv. As far as I can tell, the options specified include: no grazing and no fire (rgroup.freq0.graz.0.lowgraz.in), low grazing every year and no fire (rgroup.freq0.graz.1.lowgraz.in), and low grazing every year with fire every 50 years (rgroup.freq50.graz.1.lowgraz.in). 

More importantly - the combination rgroup.freq50.graz.0.lowgraz.in doesn't make sense. graz.0 = no grazing. So it doesn't make sense to have a grazing intensity "lowgraz" set.

Does this make sense? However if the wrapper code is expecting that combination, despite it not being requested in inputs, we indeed have a problem.

**Comment by chaukap** [comment]
This issue is resolved by commit 8735a63
