### ISSUE TITLE
Option 1,2 fixed2 is not functional for rgroup inputs

### ISSUE THREAD

**Issue by kpalmqui** [DrylandEcology/rSFSTEP2#86]
Within the rgroup inputs csv file - three different fire/grazing regimes are requested for Site 1:

1) Site = all, treatment = fixed 1: no fire, no grazing (D0.G0.lowgraz) 
2) Site = 1, treatment = specific: FRI=50, grazing every year, low grazing intensity (D.50.G1.lowgraz)
3) Site = 1,2, treatment = fixed2: FRI=75, grazing every year, low grazing intensity (D.75.G1.lowgraz)

The rgroup file for 3) is not correctly generated and put in STEPWAT_DIST and thus there is no output for D.75.G1.lowgraz. The rgroup file for 3) is copied into STEPWAT_DIST as "fixed2_vector.in".
Here is what that looks like:

[fixed2_vector.txt](https://github.com/DrylandEcology/rSFSTEP2/files/2634972/fixed2_vector.txt)

There is a problem in the code, as fixed2_vector.in is not properly inserted into rgroup_template.in and resaved as rgroup.freq75.graz.1.lowgraz.in and hence some of the output requested is not generated.

Note: for 1) - it should be labeled nograz rather than lowgraz. I will create another issue for this.

**Comment by chaukap** [comment]
While exploring this issue I ran into a related problem in the naming of Rgroup files:
The naming convention for rgroup needs to include the treatment name to prevent two files from having the same name, The convention currently in the code is 
```
"rgroup.distFreq.grazFreq.grazIntensity.in"
```
The problem with this naming contention is that distFreq, grazFreq, and grazIntensity could be the same for two different treatments. This problem could show up in larger production runs where the user is changing the "space" parameter without changing the disturbance parameters.
To solve this problem, and the problem described in the title of this issue, we should change the naming convention of rgroup files (for 'vector', 'specific' and 'all' treatment types) to
```
"rgroup.distFreq.grazFreq.grazIntensity.treatment.in"
```
Since treatments are unique identifiers we would not run into the issue of two files with the same name.
Using this convention will require a few changes to the wrapper code as well, but I believe it would make the files easier to identify.
